// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"context"
	"landan-desktop-fyne/bootstrap"
	"landan-desktop-fyne/internal/classifier"
	"landan-desktop-fyne/internal/detector"
	"landan-desktop-fyne/internal/input/application/command/ir/predictor"
	"landan-desktop-fyne/internal/input/application/recognition/ir/inference"
	"landan-desktop-fyne/internal/output/application/inference"
	"landan-desktop-fyne/internal/output/application/inference/pipeline"
	"landan-desktop-fyne/internal/usecase/application/any/ir/inference"
	"landan-desktop-fyne/internal/usecase/application/any/ir/predictor"
)

// Injectors from wire.go:

func InitRecognitionContainer(ctx context.Context, config bootstrap.Config) (*RecognitionContainer, error) {
	abstractInference, err := outputApplicationInference.NewAbstractInference(ctx, config)
	if err != nil {
		return nil, err
	}
	dieTopDetector, err := detector.NewDieTopDetector(abstractInference)
	if err != nil {
		return nil, err
	}
	dieValueClassifier, err := classifier.NewDieValueClassifier(abstractInference)
	if err != nil {
		return nil, err
	}
	diePipeline := outputApplicationInferencePipeline.NewDiePipeline(dieTopDetector, dieValueClassifier)
	dieUsecase := usecaseApplicationAnyIrInference.NewDieUsecase(diePipeline)
	dieHandler := inputApplicationRecognitionIrInference.NewDieHandler(dieUsecase)
	pokerHandler := inputApplicationRecognitionIrInference.NewPokerHandler()
	diskHandler := inputApplicationRecognitionIrInference.NewDiskHandler()
	recognitionContainer := &RecognitionContainer{
		RecognitionInferenceDie:   dieHandler,
		RecognitionInferencePoker: pokerHandler,
		RecognitionInferenceDisk:  diskHandler,
	}
	return recognitionContainer, nil
}

func InitDiePredictorCommandContainer(ctx context.Context, config bootstrap.Config) (*DiePredictorCommandContainer, error) {
	abstractInference, err := outputApplicationInference.NewAbstractInference(ctx, config)
	if err != nil {
		return nil, err
	}
	dieTopDetector, err := detector.NewDieTopDetector(abstractInference)
	if err != nil {
		return nil, err
	}
	dieValueClassifier, err := classifier.NewDieValueClassifier(abstractInference)
	if err != nil {
		return nil, err
	}
	diePipeline := outputApplicationInferencePipeline.NewDiePipeline(dieTopDetector, dieValueClassifier)
	diePredictorUsecase := usecaseApplicationAnyIrPredictor.NewDiePredictorUsecase(diePipeline)
	diePredictorHandler := inputApplicationCommandIrPredictor.NewDiePredictorHandler(diePredictorUsecase)
	diePredictorCommandContainer := &DiePredictorCommandContainer{
		DiePredictor: diePredictorHandler,
	}
	return diePredictorCommandContainer, nil
}

func InitPokerPredictorCommandContainer(ctx context.Context, config bootstrap.Config) (*PokerPredictorCommandContainer, error) {
	abstractInference, err := outputApplicationInference.NewAbstractInference(ctx, config)
	if err != nil {
		return nil, err
	}
	pokerCardDetector, err := detector.NewPokerCardDetector(abstractInference)
	if err != nil {
		return nil, err
	}
	pokerFaceClassifier, err := classifier.NewPokerFaceClassifier(abstractInference)
	if err != nil {
		return nil, err
	}
	pokerRankClassifier, err := classifier.NewPokerRankClassifier(abstractInference)
	if err != nil {
		return nil, err
	}
	pokerSuitClassifier, err := classifier.NewPokerSuitClassifier(abstractInference)
	if err != nil {
		return nil, err
	}
	pokerPipeline := outputApplicationInferencePipeline.NewPokerPipeline(pokerCardDetector, pokerFaceClassifier, pokerRankClassifier, pokerSuitClassifier)
	pokerPredictorUsecase := usecaseApplicationAnyIrPredictor.NewPokerPredictorUsecase(pokerPipeline)
	pokerPredictorHandler := inputApplicationCommandIrPredictor.NewPokerPredictorHandler(pokerPredictorUsecase)
	pokerPredictorCommandContainer := &PokerPredictorCommandContainer{
		PokerPredictor: pokerPredictorHandler,
	}
	return pokerPredictorCommandContainer, nil
}

// wire.go:

// RecognitionContainer 只給 `recognition` gRPC 服務使用。
// 目前只有 die 會載入模型，poker、disk 的 handler 還沒有相依。
type RecognitionContainer struct {

	// recognition
	RecognitionInferenceDie   *inputApplicationRecognitionIrInference.DieHandler
	RecognitionInferencePoker *inputApplicationRecognitionIrInference.PokerHandler
	RecognitionInferenceDisk  *inputApplicationRecognitionIrInference.DiskHandler
}

// DiePredictorCommandContainer 只給 `die-predictor` 指令使用，不載入 poker 的模型。
type DiePredictorCommandContainer struct {

	// command
	DiePredictor *inputApplicationCommandIrPredictor.DiePredictorHandler
}

// PokerPredictorCommandContainer 只給 `poker-predictor` 指令使用，不載入 die 的模型。
type PokerPredictorCommandContainer struct {

	// command
	PokerPredictor *inputApplicationCommandIrPredictor.PokerPredictorHandler
}
