// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: recognition/table/inference/die.proto

package pb_recognition_table_inference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DieRecognizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoded image bytes (JPEG or PNG).
	Image         []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DieRecognizeRequest) Reset() {
	*x = DieRecognizeRequest{}
	mi := &file_recognition_table_inference_die_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DieRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DieRecognizeRequest) ProtoMessage() {}

func (x *DieRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_table_inference_die_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DieRecognizeRequest.ProtoReflect.Descriptor instead.
func (*DieRecognizeRequest) Descriptor() ([]byte, []int) {
	return file_recognition_table_inference_die_proto_rawDescGZIP(), []int{0}
}

func (x *DieRecognizeRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type DieRecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Die                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DieRecognizeResponse) Reset() {
	*x = DieRecognizeResponse{}
	mi := &file_recognition_table_inference_die_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DieRecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DieRecognizeResponse) ProtoMessage() {}

func (x *DieRecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_table_inference_die_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DieRecognizeResponse.ProtoReflect.Descriptor instead.
func (*DieRecognizeResponse) Descriptor() ([]byte, []int) {
	return file_recognition_table_inference_die_proto_rawDescGZIP(), []int{1}
}

func (x *DieRecognizeResponse) GetItems() []*Die {
	if x != nil {
		return x.Items
	}
	return nil
}

type Die struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bounding box in pixels, origin at the top-left corner of the image.
	X      int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width  int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// Confidence in [0, 1].
	Confidence    float32 `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Die) Reset() {
	*x = Die{}
	mi := &file_recognition_table_inference_die_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Die) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Die) ProtoMessage() {}

func (x *Die) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_table_inference_die_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Die.ProtoReflect.Descriptor instead.
func (*Die) Descriptor() ([]byte, []int) {
	return file_recognition_table_inference_die_proto_rawDescGZIP(), []int{2}
}

func (x *Die) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Die) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Die) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Die) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Die) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_recognition_table_inference_die_proto protoreflect.FileDescriptor

const file_recognition_table_inference_die_proto_rawDesc = "" +
	"\n" +
	"%recognition/table/inference/die.proto\x12\x1epb.recognition.table.inference\"+\n" +
	"\x13DieRecognizeRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"Q\n" +
	"\x14DieRecognizeResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.pb.recognition.table.inference.DieR\x05items\"o\n" +
	"\x03Die\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence2\x84\x01\n" +
	"\n" +
	"DieService\x12v\n" +
	"\tRecognize\x123.pb.recognition.table.inference.DieRecognizeRequest\x1a4.pb.recognition.table.inference.DieRecognizeResponseB\"Z ./pb_recognition_table_inferenceb\x06proto3"

var (
	file_recognition_table_inference_die_proto_rawDescOnce sync.Once
	file_recognition_table_inference_die_proto_rawDescData []byte
)

func file_recognition_table_inference_die_proto_rawDescGZIP() []byte {
	file_recognition_table_inference_die_proto_rawDescOnce.Do(func() {
		file_recognition_table_inference_die_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recognition_table_inference_die_proto_rawDesc), len(file_recognition_table_inference_die_proto_rawDesc)))
	})
	return file_recognition_table_inference_die_proto_rawDescData
}

var file_recognition_table_inference_die_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recognition_table_inference_die_proto_goTypes = []any{
	(*DieRecognizeRequest)(nil),  // 0: pb.recognition.table.inference.DieRecognizeRequest
	(*DieRecognizeResponse)(nil), // 1: pb.recognition.table.inference.DieRecognizeResponse
	(*Die)(nil),                  // 2: pb.recognition.table.inference.Die
}
var file_recognition_table_inference_die_proto_depIdxs = []int32{
	2, // 0: pb.recognition.table.inference.DieRecognizeResponse.items:type_name -> pb.recognition.table.inference.Die
	0, // 1: pb.recognition.table.inference.DieService.Recognize:input_type -> pb.recognition.table.inference.DieRecognizeRequest
	1, // 2: pb.recognition.table.inference.DieService.Recognize:output_type -> pb.recognition.table.inference.DieRecognizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recognition_table_inference_die_proto_init() }
func file_recognition_table_inference_die_proto_init() {
	if File_recognition_table_inference_die_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recognition_table_inference_die_proto_rawDesc), len(file_recognition_table_inference_die_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recognition_table_inference_die_proto_goTypes,
		DependencyIndexes: file_recognition_table_inference_die_proto_depIdxs,
		MessageInfos:      file_recognition_table_inference_die_proto_msgTypes,
	}.Build()
	File_recognition_table_inference_die_proto = out.File
	file_recognition_table_inference_die_proto_goTypes = nil
	file_recognition_table_inference_die_proto_depIdxs = nil
}
