// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: recognition/table/inference/die.proto

package pb_recognition_table_inference

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DieService_Recognize_FullMethodName = "/pb.recognition.table.inference.DieService/Recognize"
)

// DieServiceClient is the client API for DieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DieServiceClient interface {
	// Recognize finds the dice in a single image.
	Recognize(ctx context.Context, in *DieRecognizeRequest, opts ...grpc.CallOption) (*DieRecognizeResponse, error)
}

type dieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDieServiceClient(cc grpc.ClientConnInterface) DieServiceClient {
	return &dieServiceClient{cc}
}

func (c *dieServiceClient) Recognize(ctx context.Context, in *DieRecognizeRequest, opts ...grpc.CallOption) (*DieRecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DieRecognizeResponse)
	err := c.cc.Invoke(ctx, DieService_Recognize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DieServiceServer is the server API for DieService service.
// All implementations must embed UnimplementedDieServiceServer
// for forward compatibility.
type DieServiceServer interface {
	// Recognize finds the dice in a single image.
	Recognize(context.Context, *DieRecognizeRequest) (*DieRecognizeResponse, error)
	mustEmbedUnimplementedDieServiceServer()
}

// UnimplementedDieServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDieServiceServer struct{}

func (UnimplementedDieServiceServer) Recognize(context.Context, *DieRecognizeRequest) (*DieRecognizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recognize not implemented")
}
func (UnimplementedDieServiceServer) mustEmbedUnimplementedDieServiceServer() {}
func (UnimplementedDieServiceServer) testEmbeddedByValue()                    {}

// UnsafeDieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DieServiceServer will
// result in compilation errors.
type UnsafeDieServiceServer interface {
	mustEmbedUnimplementedDieServiceServer()
}

func RegisterDieServiceServer(s grpc.ServiceRegistrar, srv DieServiceServer) {
	// If the following call panics, it indicates UnimplementedDieServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DieService_ServiceDesc, srv)
}

func _DieService_Recognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DieRecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DieServiceServer).Recognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DieService_Recognize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DieServiceServer).Recognize(ctx, req.(*DieRecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DieService_ServiceDesc is the grpc.ServiceDesc for DieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.recognition.table.inference.DieService",
	HandlerType: (*DieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recognize",
			Handler:    _DieService_Recognize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recognition/table/inference/die.proto",
}
