// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: recognition/table/inference/poker.proto

package pb_recognition_table_inference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokerRecognizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoded image bytes (JPEG or PNG).
	Image         []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokerRecognizeRequest) Reset() {
	*x = PokerRecognizeRequest{}
	mi := &file_recognition_table_inference_poker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokerRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokerRecognizeRequest) ProtoMessage() {}

func (x *PokerRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_table_inference_poker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokerRecognizeRequest.ProtoReflect.Descriptor instead.
func (*PokerRecognizeRequest) Descriptor() ([]byte, []int) {
	return file_recognition_table_inference_poker_proto_rawDescGZIP(), []int{0}
}

func (x *PokerRecognizeRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type PokerRecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Poker               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokerRecognizeResponse) Reset() {
	*x = PokerRecognizeResponse{}
	mi := &file_recognition_table_inference_poker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokerRecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokerRecognizeResponse) ProtoMessage() {}

func (x *PokerRecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_table_inference_poker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokerRecognizeResponse.ProtoReflect.Descriptor instead.
func (*PokerRecognizeResponse) Descriptor() ([]byte, []int) {
	return file_recognition_table_inference_poker_proto_rawDescGZIP(), []int{1}
}

func (x *PokerRecognizeResponse) GetItems() []*Poker {
	if x != nil {
		return x.Items
	}
	return nil
}

type Poker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Card face, e.g. "A", "10", "K".
	Rank string `protobuf:"bytes,1,opt,name=rank,proto3" json:"rank,omitempty"`
	// Card suit, e.g. "spade", "heart", "diamond", "club".
	Suit string `protobuf:"bytes,2,opt,name=suit,proto3" json:"suit,omitempty"`
	// Bounding box in pixels, origin at the top-left corner of the image.
	X      int32 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Width  int32 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	// Confidence in [0, 1].
	Confidence    float32 `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poker) Reset() {
	*x = Poker{}
	mi := &file_recognition_table_inference_poker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poker) ProtoMessage() {}

func (x *Poker) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_table_inference_poker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poker.ProtoReflect.Descriptor instead.
func (*Poker) Descriptor() ([]byte, []int) {
	return file_recognition_table_inference_poker_proto_rawDescGZIP(), []int{2}
}

func (x *Poker) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

func (x *Poker) GetSuit() string {
	if x != nil {
		return x.Suit
	}
	return ""
}

func (x *Poker) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Poker) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Poker) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Poker) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Poker) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_recognition_table_inference_poker_proto protoreflect.FileDescriptor

const file_recognition_table_inference_poker_proto_rawDesc = "" +
	"\n" +
	"'recognition/table/inference/poker.proto\x12\x1epb.recognition.table.inference\"-\n" +
	"\x15PokerRecognizeRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"U\n" +
	"\x16PokerRecognizeResponse\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.pb.recognition.table.inference.PokerR\x05items\"\x99\x01\n" +
	"\x05Poker\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\tR\x04rank\x12\x12\n" +
	"\x04suit\x18\x02 \x01(\tR\x04suit\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence2\x8a\x01\n" +
	"\fPokerService\x12z\n" +
	"\tRecognize\x125.pb.recognition.table.inference.PokerRecognizeRequest\x1a6.pb.recognition.table.inference.PokerRecognizeResponseB\"Z ./pb_recognition_table_inferenceb\x06proto3"

var (
	file_recognition_table_inference_poker_proto_rawDescOnce sync.Once
	file_recognition_table_inference_poker_proto_rawDescData []byte
)

func file_recognition_table_inference_poker_proto_rawDescGZIP() []byte {
	file_recognition_table_inference_poker_proto_rawDescOnce.Do(func() {
		file_recognition_table_inference_poker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recognition_table_inference_poker_proto_rawDesc), len(file_recognition_table_inference_poker_proto_rawDesc)))
	})
	return file_recognition_table_inference_poker_proto_rawDescData
}

var file_recognition_table_inference_poker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recognition_table_inference_poker_proto_goTypes = []any{
	(*PokerRecognizeRequest)(nil),  // 0: pb.recognition.table.inference.PokerRecognizeRequest
	(*PokerRecognizeResponse)(nil), // 1: pb.recognition.table.inference.PokerRecognizeResponse
	(*Poker)(nil),                  // 2: pb.recognition.table.inference.Poker
}
var file_recognition_table_inference_poker_proto_depIdxs = []int32{
	2, // 0: pb.recognition.table.inference.PokerRecognizeResponse.items:type_name -> pb.recognition.table.inference.Poker
	0, // 1: pb.recognition.table.inference.PokerService.Recognize:input_type -> pb.recognition.table.inference.PokerRecognizeRequest
	1, // 2: pb.recognition.table.inference.PokerService.Recognize:output_type -> pb.recognition.table.inference.PokerRecognizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recognition_table_inference_poker_proto_init() }
func file_recognition_table_inference_poker_proto_init() {
	if File_recognition_table_inference_poker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recognition_table_inference_poker_proto_rawDesc), len(file_recognition_table_inference_poker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recognition_table_inference_poker_proto_goTypes,
		DependencyIndexes: file_recognition_table_inference_poker_proto_depIdxs,
		MessageInfos:      file_recognition_table_inference_poker_proto_msgTypes,
	}.Build()
	File_recognition_table_inference_poker_proto = out.File
	file_recognition_table_inference_poker_proto_goTypes = nil
	file_recognition_table_inference_poker_proto_depIdxs = nil
}
